### ISSUE TITLE
$returnRaw 只有一处使用

### ISSUE THREAD

**Issue by ydPro-G** [hedeqiang/easyjiguang#27]
您好，在BaseClient.php文件中，request函数中
return $returnRaw ? $response : $this->castResponseToType($response, $this->app->config->get('response_type'));

$returnRaw 并没有一处使用，所以在laravel使用中会报错

**Comment by hedeqiang** [comment]
Laravel 什么版本？ 我在laravel 下测试了

**Comment by ydPro-G** [comment]
> Laravel 什么版本？ 我在laravel 下测试了 ，我也在用laravel

laravel 8
第一次跑提示
![image](https://user-images.githubusercontent.com/46178109/132784552-5155b074-e673-4a0f-af6f-104870b34cc6.png)

将HasHttpRequests.php文件中，pushMiddleware函数 `protected function pushMiddleware(callable $middleware, string $name = null):HasHttpRequests` 中HasHttpRequests去掉后重新再跑，这时会提示
![image](https://user-images.githubusercontent.com/46178109/132784808-007ff246-2889-4c1b-bf72-f4166104f18d.png)
这时发现$returnRaw只有一处使用

**Comment by hedeqiang** [comment]
@ydPro-G   composer update 下，
